voice_group musical_hall
	.rept 10
		voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample196, 224, 245, 0, 200 @ 10
	.rept 34
		voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample068, 255, 235, 0, 165 @ 45
	.rept 2
		voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_60, 255, 0, 255, 196 @ 48
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 49
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 50
	.rept 9
		voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample090, 255, 245, 140, 215 @ 60
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 61
	.rept 7
		voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 69
	.rept 58
		voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
