
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                            0
#define PARTNER_STEVEN                          1
#define PARTNER_CHEREN_WELLSPRINGCAVE_TEPIG     2
#define PARTNER_CHEREN_WELLSPRINGCAVE_OSHAWOTT  3
#define PARTNER_CHEREN_WELLSPRINGCAVE_SNIVY     4
#define PARTNER_CHEREN_ROUTE5_TEPIG             5
#define PARTNER_CHEREN_ROUTE5_OSHAWOTT          6
#define PARTNER_CHEREN_ROUTE5_SNIVY             7
#define PARTNER_COUNT                           8

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
