Text_PictureBookShelf:
	.string "There's a set of POKéMON picture books.$"

Text_BookShelf:
	.string "The shelves are jammed with vibrant\n"
	.string "Pokémon goods.$"

Text_PokemonCenterBookShelf:
	.string "The shelves are jammed with vibrant\n"
	.string "Pokémon goods.$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "The trash can is empty.$"

Text_ShopShelf:
	.string "The shelves brim with all sorts of\n"
	.string "POKéMON merchandise.$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"

Text_KitchenShelf:
	.string "Goods are arranged on the shelves in a\n"
	.string "very orderly fashion.$"
	
Text_TripleDrawer:
	.string "It's lined with Pokémon picture books.$"
	
Text_BookCase:
	.string "It's chock full of Pokémon books and\n"
	.string "photo collections.$"
