Common_Movement_WalkUpOnce:
	walk_up
	step_end

Common_Movement_WalkDownOnce:
	walk_down
	step_end

Common_Movement_WalkLeftOnce:
	walk_left
	step_end

Common_Movement_WalkRightOnce:
	walk_right
	step_end

Common_Movement_WalkInPlaceUp:
	walk_in_place_up
	step_end 

Common_Movement_WalkUpTwice:
	walk_up
	walk_up
	step_end

Common_Movement_WalkDownTwice:
	walk_down
	walk_down
	step_end

Common_Movement_WalkLeftTwice:
	walk_left
	walk_left
	step_end

Common_Movement_WalkRightTwice:
	walk_right
	walk_right
	step_end
