XTransceiver_Text_XTransceiverIsRinging::
	.string "The Xtransceiver is ringing.\p"
	.string "{PLAYER} picked up the Xtransceiver.$"

CherenBattle_Text_SoThatsPokemonBattle::
	.string "Ah! So that's a Pokémon battle!$"

CherenBattle_Text_WhyDoYouKeepBeatingMe::
	.string "Why do you keep beating me?\p"
	.string "We have the same number\n"
	.string "of Gym Badges.\p"
	.string "We should be equals\n"
	.string "in strength...$"

CherenBattle_Text_ImpressiveButWhyCantIWin::
	.string "Impressive.\n"
	.string "But why can't I win?!$"

CherenBattle_Text_YouAreStrongAsUsual::
	.string "Well! You are strong, as usual!$"

CherenBattle_Text_LosingMeansLotToLearn::
	.string "I see!\p"
	.string "Losing to you means\n"
	.string "that I still have a lot to learn.$"

BiancaBattle_Text_TrainedWithIris::
	.string "I trained with Iris...\n"
	.string "But I still couldn't win...$"

BiancaBattle_Text_PokemonOnBothSides::
	.string "The Pokémon on both sides\n"
	.string "did their best!$"

BiancaBattle_Text_AwwICouldntWin::
	.string "Aww...\n"
	.string "I couldn't win...$"

Elevator_Text_WhichFloorWouldLikeToGo::
	.string "Which floor would you like to go to?$"





