XTransceiver_Text_XTransceiverIsRinging::
	.string "The Xtransceiver is ringing.\p"
	.string "{PLAYER} picked up the Xtransceiver.$"

CherenBattle_Text_SoThatsPokemonBattle::
	.string "Ah! So that's a Pokémon battle!$"

CherenBattle_Text_WhyDoYouKeepBeatingMe::
	.string "Why do you keep beating me?\p"
	.string "We have the same number\n"
	.string "of Gym Badges.\p"
	.string "We should be equals\n"
	.string "in strength...$"

CherenBattle_Text_ImpressiveButWhyCantIWin::
	.string "Impressive.\n"
	.string "But why can't I win?!$"

CherenBattle_Text_YouAreStrongAsUsual::
	.string "Well! You are strong, as usual!$"

CherenBattle_Text_LosingMeansLotToLearn::
	.string "I see!\p"
	.string "Losing to you means\n"
	.string "that I still have a lot to learn.$"

BiancaBattle_Text_TrainedWithIris::
	.string "I trained with Iris...\n"
	.string "But I still couldn't win...$"

BiancaBattle_Text_PokemonOnBothSides::
	.string "The Pokémon on both sides\n"
	.string "did their best!$"

BiancaBattle_Text_AwwICouldntWin::
	.string "Aww...\n"
	.string "I couldn't win...$"

Elevator_Text_WhichFloorWouldLikeToGo::
	.string "Which floor would you like to go to?$"

DreamYard_Text_DoYouWantThisMonkey::
	.string "{STR_VAR_1}! Really?\n"
	.string "Then {STR_VAR_2} could be a big help!\p"
	.string "Your Snivy does not do well against\n"
	.string "{STR_VAR_3}-type Pokémon!\p"
	.string "Say, do you want this {STR_VAR_2} of mine?$"

DreamYard_Text_DoYouWantThisMonkeyAskAgain::
	.string "Your {STR_VAR_1} does not do well against\n"
	.string "{STR_VAR_3}-type Pokémon!\p"
	.string "Say, do you want this {STR_VAR_2} of mine?$"

DreamYard_Text_HereIsYourMonkey::
	.string "OK. Here you go!\p"
	.string "It can use {STR_VAR_1}-type moves, so that\n"
	.string "makes it great against {STR_VAR_2} types!$"

DreamYard_Text_PlayerObtainedMonkey::
	.string "{PLAYER} received {STR_VAR_3}!$"

DreamYard_Text_MonkeySentToPC::
	.string "{STR_VAR_3} was sent to the PC!$"

General_Text_PokemonStorageIsFull::
	.string "Your Pokémon Storage is full...$"

CasteliaCity_Text_OneCone::
	.string "   1 Cone      ¥100$"

CasteliaCity_Text_DozenCone::
	.string " 12 CONES   ¥1,200"
	
	
	



