Nuvema_Town_MapScripts::
	.byte 0

Nuvema_Town_SignPost::
	msgbox Nuvema_Town_SignPost_Text_0, MSGBOX_SIGN
	end

Nuvema_Town_JuniperLabSign::
	msgbox Nuvema_Town_JuniperLabSign_Text_0, MSGBOX_SIGN
	end

Nuvema_Town_PlayersHouseSign::
	msgbox Nuvema_Town_PlayersHouseSign_Text_0, MSGBOX_SIGN
	end

Nuvema_Town_BiancasHouseSign::
	msgbox Nuvema_Town_BiancasHouseSign_Text_0, MSGBOX_SIGN
	end

Nuvema_Town_CherensHouseSign::
	msgbox Nuvema_Town_CherensHouseSign_Text_0, MSGBOX_SIGN
	end

Nuvema_Town_EventScript_LittleGirl::
	msgbox Nuvema_Town_LittleGirl_Text_0, MSGBOX_NPC
	end

Nuvema_Town_SignPost_Text_0:
	.string "Nuvema Town\n"
	.string "The Start of Something Big!$"

Nuvema_Town_JuniperLabSign_Text_0:
	.string "Juniper Pokémon Lab$"

Nuvema_Town_PlayersHouseSign_Text_0:
	.string "{PLAYER}'s House$"

Nuvema_Town_BiancasHouseSign_Text_0:
	.string "Bianca's House$"

Nuvema_Town_CherensHouseSign_Text_0:
	.string "Cheren's House$"

Nuvema_Town_LittleGirl_Text_0:
	.string "I've heard there are a lot of Pokémon\n"
	.string "abd many different people in the world.\p"
	.string "When I hear stories about them,\n"
	.string "I get very excited!$"
